# Generated by Django 3.0.7 on 2020-11-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPDDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpd_number', models.CharField(max_length=20)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ECDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_number', models.CharField(max_length=20)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kegg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ec_number', models.CharField(max_length=20)),
                ('cpd', models.CharField(max_length=20)),
            ],
        ),
    ]
